import { useState, useEffect, useRef } from 'react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';
import { Eye, ThumbsUp, Clock, TrendingUp, Calendar, Download, FileText } from 'lucide-react';
import { ALL_VIDEOS, CATEGORIES } from '../data/videosData';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

const AnalyticsPage = () => {
  const [analyticsData, setAnalyticsData] = useState({
    totalViews: 0,
    totalLikes: 0,
    watchTime: 0,
    mostViewedCategory: '',
    dailyViews: [] as any[],
    categoryDistribution: [] as any[],
    popularVideos: [] as any[]
  });
  
  const [exporting, setExporting] = useState(false);
  const analyticsRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const views = JSON.parse(localStorage.getItem('videoViews') || '{}');
    const likes = JSON.parse(localStorage.getItem('videoLikes') || '{}');
    const watchHistory = JSON.parse(localStorage.getItem('watchHistory') || '[]');

    const categoryViews: Record<string, number> = {};
    ALL_VIDEOS.forEach(video => {
      const category = video.category || 'Other';
      categoryViews[category] = (categoryViews[category] || 0) + (views[video.id] || 0);
    });

    let maxViews = 0;
    let mostViewedCategory = '';
    Object.entries(categoryViews).forEach(([cat, count]) => {
      if (count > maxViews) {
        maxViews = count;
        mostViewedCategory = cat;
      }
    });

    // Prepare category distribution for pie chart
    const categoryDistribution = Object.entries(categoryViews).map(([name, value]) => ({
      name,
      value,
      icon: CATEGORIES.find(c => c.name === name)?.icon || '📹'
    }));

    const last7Days = Array.from({ length: 7 }, (_, i) => {
      const date = new Date();
      date.setDate(date.getDate() - i);
      return date.toISOString().split('T')[0];
    }).reverse();

    const dailyViews = last7Days.map(date => ({
      date,
      views: watchHistory.filter((h: any) => h.date === date).length
    }));

    const popularVideos = ALL_VIDEOS
      .map(video => ({
        ...video,
        views: views[video.id] || 0,
        likes: likes[video.id] || 0
      }))
      .sort((a, b) => b.views - a.views)
      .slice(0, 5);

    const viewsValues = Object.values(views) as number[];
    const likesValues = Object.values(likes) as number[];
    
    setAnalyticsData({
      totalViews: viewsValues.reduce((a, b) => a + b, 0),
      totalLikes: likesValues.reduce((a, b) => a + b, 0),
      watchTime: watchHistory.length * 5,
      mostViewedCategory,
      dailyViews,
      categoryDistribution,
      popularVideos
    });
  }, []);

  const COLORS = ['#0088FE', '#00C49F', '#FFBB28', '#FF8042', '#8884D8', '#82CA9D', '#FF6B6B', '#4ECDC4'];

  const renderLabel = (entry: any) => {
    const percent = entry.percent || 0;
    return `${entry.name}: ${(percent * 100).toFixed(0)}%`;
  };

  const exportToPDF = async () => {
    if (!analyticsRef.current) return;
    
    setExporting(true);
    
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      
      const canvas = await html2canvas(analyticsRef.current, {
        scale: 2,
        backgroundColor: '#ffffff',
        logging: false,
        useCORS: true
      });
      
      const imgData = canvas.toDataURL('image/png');
      const imgHeight = (canvas.height * pageWidth) / canvas.width;
      
      pdf.setFontSize(20);
      pdf.setTextColor(124, 58, 237);
      pdf.text('DevShare Analytics Report', pageWidth / 2, 30, { align: 'center' });
      
      pdf.setFontSize(10);
      pdf.setTextColor(100, 100, 100);
      pdf.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, 45, { align: 'center' });
      
      pdf.addImage(imgData, 'PNG', 0, 60, pageWidth, imgHeight);
      
      pdf.setFontSize(9);
      pdf.setTextColor(150, 150, 150);
      pdf.text(
        'Generated by DevShare',
        pageWidth / 2,
        pdf.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
      
      pdf.save(`devshare-analytics-${new Date().toISOString().split('T')[0]}.pdf`);
      
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Failed to generate PDF. Please try again.');
    } finally {
      setExporting(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-8">
      <div className="container mx-auto px-4">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-8">
          <h1 className="text-3xl font-bold text-gray-800 dark:text-white flex items-center gap-2">
            <TrendingUp size={28} /> Analytics Dashboard
          </h1>
          <div className="flex gap-3">
            <button
              onClick={exportToPDF}
              disabled={exporting}
              className="flex items-center gap-2 bg-gradient-to-r from-purple-600 to-blue-600 text-white px-5 py-2.5 rounded-lg hover:from-purple-700 hover:to-blue-700 transition disabled:opacity-50 shadow-md"
            >
              {exporting ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-2 border-white border-t-transparent"></div>
                  Generating...
                </>
              ) : (
                <>
                  <Download size={18} />
                  Export as PDF
                </>
              )}
            </button>
            <button
              onClick={() => window.print()}
              className="flex items-center gap-2 bg-gray-600 text-white px-5 py-2.5 rounded-lg hover:bg-gray-700 transition shadow-md"
            >
              <FileText size={18} />
              Print Report
            </button>
          </div>
        </div>
        <div ref={analyticsRef} className="space-y-8">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-500 dark:text-gray-400 text-sm">Total Views</p>
                  <p className="text-2xl font-bold text-gray-800 dark:text-white">{analyticsData.totalViews.toLocaleString()}</p>
                </div>
                <Eye size={40} className="text-blue-500" />
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-500 dark:text-gray-400 text-sm">Total Likes</p>
                  <p className="text-2xl font-bold text-gray-800 dark:text-white">{analyticsData.totalLikes.toLocaleString()}</p>
                </div>
                <ThumbsUp size={40} className="text-green-500" />
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-500 dark:text-gray-400 text-sm">Watch Time (min)</p>
                  <p className="text-2xl font-bold text-gray-800 dark:text-white">{analyticsData.watchTime.toLocaleString()}</p>
                </div>
                <Clock size={40} className="text-purple-500" />
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-500 dark:text-gray-400 text-sm">Top Category</p>
                  <p className="text-2xl font-bold text-gray-800 dark:text-white">
                    {analyticsData.mostViewedCategory || 'None'}
                  </p>
                </div>
                <TrendingUp size={40} className="text-orange-500" />
              </div>
            </div>
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6">
              <h2 className="text-xl font-semibold text-gray-800 dark:text-white mb-4 flex items-center gap-2">
                <Calendar size={20} /> Daily Views (Last 7 Days)
              </h2>
              <ResponsiveContainer width="100%" height={300}>
                <LineChart data={analyticsData.dailyViews}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="date" />
                  <YAxis />
                  <Tooltip />
                  <Legend />
                  <Line type="monotone" dataKey="views" stroke="#8884d8" activeDot={{ r: 8 }} />
                </LineChart>
              </ResponsiveContainer>
            </div>

            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6">
              <h2 className="text-xl font-semibold text-gray-800 dark:text-white mb-4">Category Distribution</h2>
              <ResponsiveContainer width="100%" height={300}>
                <PieChart>
                  <Pie
                    data={analyticsData.categoryDistribution}
                    cx="50%"
                    cy="50%"
                    labelLine={false}
                    label={renderLabel}
                    outerRadius={80}
                    fill="#8884d8"
                    dataKey="value"
                  >
                    {analyticsData.categoryDistribution.map((_entry: any, index: number) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </div>
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6">
            <h2 className="text-xl font-semibold text-gray-800 dark:text-white mb-4">Most Popular Videos</h2>
            <div className="space-y-4">
              {analyticsData.popularVideos.length === 0 ? (
                <p className="text-gray-500 dark:text-gray-400 text-center py-8">No data yet. Watch some videos!</p>
              ) : (
                analyticsData.popularVideos.map((video: any, index: number) => (
                  <div key={video.id} className="flex items-center gap-4 p-4 border border-gray-200 dark:border-gray-700 rounded-lg">
                    <div className="text-2xl font-bold text-gray-400 w-10">#{index + 1}</div>
                    <img src={video.thumbnail} alt={video.title} className="w-24 h-16 object-cover rounded" />
                    <div className="flex-1">
                      <h3 className="font-semibold text-gray-800 dark:text-white">{video.title}</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">{video.channelTitle}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-sm text-gray-500">Views</p>
                      <p className="font-semibold text-gray-800 dark:text-white">{video.views.toLocaleString()}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-sm text-gray-500">Likes</p>
                      <p className="font-semibold text-gray-800 dark:text-white">{video.likes.toLocaleString()}</p>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AnalyticsPage;